// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJgeuiBqjV434qoTWnBWt1a9Z7nFLKA_E',
    appId: '1:295199946538:web:be70299851b6f903fe1053',
    messagingSenderId: '295199946538',
    projectId: 'cimotecarm',
    authDomain: 'cimotecarm.firebaseapp.com',
    databaseURL: 'https://cimotecarm-default-rtdb.firebaseio.com',
    storageBucket: 'cimotecarm.firebasestorage.app',
    measurementId: 'G-Y5GYJY0LRB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_rBpfkPKRm1tDIDOd8YWDR72nA3IN6y0',
    appId: '1:295199946538:android:8eababea5eb5dee4fe1053',
    messagingSenderId: '295199946538',
    projectId: 'cimotecarm',
    databaseURL: 'https://cimotecarm-default-rtdb.firebaseio.com',
    storageBucket: 'cimotecarm.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQNRsxN2RLCvQHTrSjZp6H9pCu5-5XwGU',
    appId: '1:295199946538:ios:0867581a0f72965afe1053',
    messagingSenderId: '295199946538',
    projectId: 'cimotecarm',
    databaseURL: 'https://cimotecarm-default-rtdb.firebaseio.com',
    storageBucket: 'cimotecarm.firebasestorage.app',
    iosBundleId: 'com.example.cibleMilitaire',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQNRsxN2RLCvQHTrSjZp6H9pCu5-5XwGU',
    appId: '1:295199946538:ios:0867581a0f72965afe1053',
    messagingSenderId: '295199946538',
    projectId: 'cimotecarm',
    databaseURL: 'https://cimotecarm-default-rtdb.firebaseio.com',
    storageBucket: 'cimotecarm.firebasestorage.app',
    iosBundleId: 'com.example.cibleMilitaire',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJgeuiBqjV434qoTWnBWt1a9Z7nFLKA_E',
    appId: '1:295199946538:web:892e8a4137e570b1fe1053',
    messagingSenderId: '295199946538',
    projectId: 'cimotecarm',
    authDomain: 'cimotecarm.firebaseapp.com',
    databaseURL: 'https://cimotecarm-default-rtdb.firebaseio.com',
    storageBucket: 'cimotecarm.firebasestorage.app',
    measurementId: 'G-5YC322GX9Z',
  );
}
